name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ cmake make
      - name: Create build directory
        run: mkdir build
      - name: Run CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
